spring.application.name=intuition-portal

# Database Connection (Flexible for Local and Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/central_portal_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Abhi@2007}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Add this to help Spring find the dialect if the connection is slow
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect