spring.application.name=intuition-portal

# Server
server.port=${PORT:8080}

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-13d086e5-fullstack-01.a.aivencloud.com:12202/defaultdb?ssl-mode=REQUIRE&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_JhS5xygJ9arZ5b5Zx48}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect