spring.datasource.url=jdbc:mysql://localhost:3306/intuition_portal
spring.datasource.username=root
# IMPORTANT: Put your actual MySQL password here!
spring.datasource.password=Abhi@2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true